export interface Product {
    id: number;
    name: string;
    price: number;
    discountPrice?: number;
    img: string;
    rating: number;
    category: string;
    isNew?: boolean;
}

export const PRODUCT_CATEGORIES = {
    DAIRY: "Молочные продукты",
    FROZEN: "Замороженные продукты",
    GROCERY: "Бакалея",
    FRUITS: "Фрукты и овощи",
    BAKERY: "Хлебобулочные изделия",
    CONFECTIONERY: "Кондитерские изделия",
    SEAFOOD: "Морские продукты",
    AGRICULTURAL: "Сельскохозяйственные продукты",
    MEAT: "Мясные продукты",
} as const;

export const products: Product[] = [
    {
        id: 1,
        name: "Масло сливочное",
        price: 299.99,
        discountPrice: 259.99,
        img: "maslo.png",
        rating: 4.5,
        category: PRODUCT_CATEGORIES.DAIRY,
        isNew: true,
    },
    {
        id: 2,
        name: "Г/Ц Блинчики с мясом",
        price: 299,
        discountPrice: 269,
        img: "pancakes.png",
        rating: 4.2,
        category: PRODUCT_CATEGORIES.FROZEN,
        isNew: true,
    },
    {
        id: 3,
        name: "Сыр Российский",
        price: 399.99,
        discountPrice: 349.99,
        img: "cheese.png",
        rating: 4.8,
        category: PRODUCT_CATEGORIES.DAIRY,
    },
    {
        id: 4,
        name: "Мороженое пломбир",
        price: 149.99,
        discountPrice: 129.99,
        img: "icecream.png",
        rating: 4.6,
        category: PRODUCT_CATEGORIES.FROZEN,
    },
    {
        id: 5,
        name: "Кофе молотый",
        price: 499.99,
        discountPrice: 449.99,
        img: "coffee.png",
        rating: 4.7,
        category: PRODUCT_CATEGORIES.GROCERY,
    },
    {
        id: 6,
        name: "Яблоки красные",
        price: 129.99,
        discountPrice: 109.99,
        img: "apple.png",
        rating: 4.4,
        category: PRODUCT_CATEGORIES.FRUITS,
    },
    {
        id: 7,
        name: "Хлеб белый",
        price: 89.99,
        discountPrice: 79.99,
        img: "bread.png",
        rating: 4.3,
        category: PRODUCT_CATEGORIES.BAKERY,
    },
    {
        id: 8,
        name: "Печенье овсяное",
        price: 199.99,
        discountPrice: 179.99,
        img: "cookies.png",
        rating: 4.5,
        category: PRODUCT_CATEGORIES.CONFECTIONERY,
    },
    {
        id: 9,
        name: "Молоко 3.2%",
        price: 159.99,
        discountPrice: 140,
        img: "milk.png",
        rating: 4.5,
        category: PRODUCT_CATEGORIES.DAIRY,
    },
    {
        id: 10,
        name: "Йогурт натуральный",
        price: 129.99,
        discountPrice: 110.99,
        img: "yogurt.png",
        rating: 4.4,
        category: PRODUCT_CATEGORIES.DAIRY,
    },
    {
        id: 11,
        name: "Сырок советские традиции",
        price: 39.99,
        discountPrice: 32.99,
        img: "cheesep.png",
        rating: 4.5,
        category: PRODUCT_CATEGORIES.CONFECTIONERY,
    },
    {
        id: 12,
        name: "Шпроты классические",
        price: 399.99,
        discountPrice: 382.99,
        img: "sprat.png",
        rating: 4.5,
        category: PRODUCT_CATEGORIES.SEAFOOD,
    },
    {
        id: 13,
        name: "Сливки Станция молочная",
        price: 129.99,
        discountPrice: 121.99,
        img: "cream_milk.png",
        rating: 4.5,
        category: PRODUCT_CATEGORIES.DAIRY,
    },
    {
        id: 14,
        name: "Рис Агроальянс",
        price: 399.99,
        discountPrice: 380.99,
        img: "rice.png",
        rating: 4.8,
        category: PRODUCT_CATEGORIES.AGRICULTURAL,
    },
    {
        id: 15,
        name: "Сосиски молочные",
        price: 399.99,
        discountPrice: 398.99,
        img: "sausa.png",
        rating: 4.8,
        category: PRODUCT_CATEGORIES.MEAT,
    },
    {
        id: 16,
        name: "Сыр Российский",
        price: 399.99,
        discountPrice: 320.99,
        img: "cheese.png",
        rating: 4.8,
        category: PRODUCT_CATEGORIES.DAIRY,
    },
    {
        id: 17,
        name: "Макароны от Федорыча",
        price: 399.99,
        discountPrice: 378.99,
        img: "pasta.png",
        rating: 4.8,
        category: PRODUCT_CATEGORIES.AGRICULTURAL,
    },
    {
        id: 18,
        name: "Мясо свинины",
        price: 999.99,
        discountPrice: 980.99,
        img: "pig.png",
        rating: 4.8,
        category: PRODUCT_CATEGORIES.MEAT,
    },
];
